In [1]:
import numpy as np

In [38]:
inputs = np.array([0.5, -0.2, 0.1])
targets = np.array([0.4])
lr = 0.5
weights_input_to_hidden = np.array([[0.1, -0.2],
                                    [0.4, 0.5],
                                    [-0.3, 0.2]])
weights_hidden_to_output = np.array([[0.3],
                                     [-0.1]])
hidden_inputs = np.dot(inputs, weights_input_to_hidden)
hidden_inputs

array([-0.06, -0.18])

In [39]:
activation_function = lambda x : 1 / (1 + np.exp(-x))
hidden_outputs = activation_function(hidden_inputs)
hidden_outputs

array([ 0.4850045 ,  0.45512111])

In [40]:
final_inputs = np.dot(hidden_outputs, weights_hidden_to_output)
final_outputs = final_inputs
final_inputs

array([ 0.09998924])

In [41]:
error = targets - final_outputs
error

array([ 0.30001076])

In [42]:
output_error_term = error * final_inputs
output_error_term

array([ 0.02999785])

In [43]:
hidden_error = np.dot(output_error_term, weights_hidden_to_output.T)
hidden_error

array([ 0.00899935, -0.00299978])

In [44]:
hidden_error_term = hidden_error * hidden_outputs * (1 - hidden_outputs)
hidden_error_term

array([ 0.00224781, -0.0007439 ])

In [46]:
delta_weights_i_h = np.zeros(weights_input_to_hidden.shape)
delta_weights_h_o = np.zeros(weights_hidden_to_output.shape)
delta_weights_i_h += lr * hidden_error_term * inputs[:, None]
delta_weights_i_h

array([[  5.61953733e-04,  -1.85976070e-04],
       [ -2.24781493e-04,   7.43904279e-05],
       [  1.12390747e-04,  -3.71952140e-05]])

In [48]:
inputs

array([ 0.5, -0.2,  0.1])

In [49]:
hidden_outputs.T

array([ 0.4850045 ,  0.45512111])

In [51]:
delta_weights_h_o += lr * output_error_term * hidden_outputs[:, None]
delta_weights_h_o

array([[ 0.00727455],
       [ 0.00682633]])